#!/usr/bin/env bash

### INFO #######################################################################
### Requirements: multilib enabled, internet conection is present.
### Feel free to modify script according to your needs.
### Script written using STRUCTURED paradigm with no jumps.
### Script uses autoconfig scripts provided in my other repos e.g. dot_hyprland.
### Script is designed for a fresh install with little preconfiguration, examine
###   before using in non-fresh environment due to possible overwriting.
########################################################## 2025-11-30 ### bk ###

### OPTIONAL ###################################################################
### set 1 if you want to install something from this list, if you want to add
### something that is not here -> add to APPLICATIONS list

STEAM="0"     # steam
MINECRAFT="0" # prismlauncher
EMULATORS="0" # pcsx2, rpcs3, xnp2

LATEX="0"      # texlive, biber
ASEPRITE="0"   # aseprite (compile from AUR)
BETTERBIRD="0" # betterbird-bin
NEOTHESIA="0"  # neothesia (compile from AUR)

RUST="0"     # rust
REIHA="0"    # reiha (tool for presentations)
TESUTERU="0" # testownik-cli (alternative for testownik)
TOOLS="0"    # simple cli tools (like stopwatch, timer etc.)

################################################################################

### VARIABLES ##################################################################
### only modify if you know what you are doing

TMP_FOLDER="arch_druid_temp_folder"
RST_PATH="$HOME/$TMP_FOLDER"
SESSION="none"
GPU_VENDOR="none"

### GPU
INTEL_PACKAGES=(
	vulkan-intel
	lib32-vulkan-intel
	xf86-video-intel
)

AMD_PACKAGES=(
	vulkan-radeon
	lib32-vulkan-radeon
	xf86-video-amdgpu
)

NVIDIA_PACKAGES=(
	nvidia-open-dkms
	nvidia-utils
	lib32-nvidia-utils
)

### BASE
BASE_PACKAGES=(
	base
	base-devel
	linux-zen-headers
	# linux-lts-headers
)

### SESSION
HYPR_SESSION=(
	wayland
	xorg-xwayland
	uwsm
	hyprland
	xdg-desktop-portal-gtk
	xdg-desktop-portal-hyprland
	wl-clipboard
	hyprlock
	hyprpolkitagent
	grim
	slurp
	hyprsunset
	hyprpicker
	mako
	swaybg
	waybar
	qt5-wayland
	qt6-wayland
	hyprqt6engine-git
	imv
	tofi
)

RIVER_SESSION=(
	wayland
	xorg-xwayland
	river
	xdg-desktop-portal-wlr
	xdg-desktop-portal-gtk
	wl-clipboard
	wlr-randr
	hyprpolkitagent
	hyprlock
	grim
	slurp
	mako
	swaybg
	waybar
	imv
	tofi
	qt5-wayland
	qt6-wayland
	qt6ct
)

DWM_SESSION=(
	xorg
	xorg-xinit
	dmenu
	j4-dmenu-desktop
	flameshot
	picom
	redshift
	feh
	dunst
	betterlockscreen # AUR
	qt6ct
)

### Other
TERMINAL=(
	bat
	btop
	dust
	fastfetch
	fzf
	github-cli
	htop
	imagemagick
	jp2a
	kitty
	man-db
	neovim
	ripgrep
	tldr
	tmux
	tree
	tree-sitter-cli
	udisks2
	arch-wiki-docs
)

BASIC=(
	lib32-mesa
	networkmanager
	bluez
	bluez-utils
	xpadneo-dkms # AUR
	thermald
	auto-cpufreq # AUR
	brightnessctl
	network-manager-applet
	playerctl
	noto-fonts
	noto-fonts-cjk
	noto-fonts-emoji
	noto-fonts-extra
)

DEVELOPMENT=(
	clang
	make
	cmake
	odin
	raylib
	docker
	electron
)

APPLICATIONS=(
	audacity
	carla
	krita
	lutris
	mpv
	obs-studio
	pavucontrol
	pcmanfm
	qbittorrent
	qutebrowser
	reaper
	shotcut
	tailscale
	telegram-desktop
	zathura
	zathura-pdf-mupdf
	bluetuith-bin # AUR
	proton-ge-custom-bin # AUR
	anki-bin # AUR
	blockbench-bin # AUR
	vesktop-bin # AUR
	localsend-bin # AUR
)

SOUND=(
	wireplumber
	qjackctl
	alsa-utils
	pipewire
	lib32-pipewire
	pipewire-alsa
	lib32-alsa-plugins
	pipewire-jack
	lib32-pipewire-jack
	pipewire-pulse
	gst-plugin-pipewire
	timidity++
	freepats-general-midi
	sof-firmware
)

WINE=(
	wine-staging
	wine-mono
)

THEMING=(
	gtk3
	gtk4
	papirus-icon-theme
	materia-gtk-theme
	nwg-look
	kvantum
)

BROWSERS=(
	brave-bin # AUR
	firefox
	chromium
	# librewolf-bin # AUR
)

SEPARATOR='
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
'
################################################################################

### SCRIPT INIT ################################################################
echo "Prerequisites: You have a minimal Arch Linux install with the linux-zen kernel"
echo "$SEPARATOR"


printf  "%s\n%s\n%s\n%s\n" \
	"Your GPU?" \
	"1) INTEL [thinkpad x220]" \
	"2) AMD [thinkpad t14]" \
	"3) NVIDIA TURING+ [acer NITRO RTX 3060]"
read -rp "Choice (1-3): " choice

case "$choice" in
	1)
		GPU_VENDOR="intel"
		;;
	2)
		GPU_VENDOR="amd"
		;;
	3)
		GPU_VENDOR="nvidia"
		;;
	*)
		echo "Invalid choice. Exiting."
		exit 1
		;;
esac
echo "$SEPARATOR"


printf  "%s\n%s\n" \
	"$GPU_VENDOR chosen" \
	"needed drivers will be installed"
echo "$SEPARATOR"


printf  "%s\n%s\n%s\n%s\n%s\n" \
	"Choose Session Type" \
	"Leave empty for none" \
	"1) Hyprland" \
	"2) River" \
	"3) DWM"
read -rp "Choice: " choice

case "$choice" in
	1)
		SESSION="hyprland"
		;;
	2)
		SESSION="river"
		;;
	3)
		SESSION="dwm"
		;;
	*)
		SESSION="none"
		;;
esac
echo "$SEPARATOR"

echo "$SESSION chosen"
echo "$SEPARATOR"
################################################################################

### SCRIPT INIT ################################################################
printf "%s" "Druid will begin a ritual in "
printf "%s" "5.."
sleep 1
printf "%s" "4.."
sleep 1
printf "%s" "3.."
sleep 1
printf "%s" "2.."
sleep 1
printf "%s\n" "1.."
echo "$SEPARATOR"
sleep 1


cd $HOME
echo "creating temporary $TMP_FOLDER at $HOME"
mkdir $TMP_FOLDER
cd $RST_PATH
echo "$SEPARATOR"


echo "updating system"
sudo pacman -Syu
echo "$SEPARATOR"


echo "ensuring base are installed"
sudo pacman -S --needed "${BASE_PACKAGES[@]}"
sudo pacman -S --needed "${DEVELOPMENT[@]}"
echo "$SEPARATOR"


echo "installing git if absent"
sudo pacman -S --needed git
echo "$SEPARATOR"


echo "downloading paru"
git clone https://aur.archlinux.org/paru.git
echo "$SEPARATOR"


echo "downloading dotfiles"
case "$SESSION" in
	hyprland)
		git clone https://github.com/barysk/dot_hyprland
		;;
	river)
		git clone https://github.com/barysk/dot_river
		;;
	dwm)
		git clone https://github.com/barysk/dot_dwm
		;;
	*)
		echo "No session since SESSION = $SESSION"
		;;
esac
git clone https://github.com/barysk/nvim
git clone https://github.com/barysk/seine_layout
echo "$SEPARATOR"


echo "installing paru"
cd paru
makepkg -sri
cd $RST_PATH
echo "$SEPARATOR"


echo "Installing packages"
paru -S --needed "${BASIC[@]}"
paru -S --needed "${TERMINAL[@]}"
paru -S --needed "${APPLICATIONS[@]}"
paru -S --needed "${SOUND[@]}"
paru -S --needed "${WINE[@]}"
paru -S --needed "${THEMING[@]}"
paru -S --needed "${BROWSERS[@]}"


echo "applying dotfiles"
# nvim
cd nvim
rm -rf .git
cd $RST_PATH
mv nvim $HOME/.config/
cd seine_layout
./install.sh
cd $RST_PATH
case "$SESSION" in
	hyprland)
		cd dot_hyprland
		./autoconf deploy
		cd $RST_PATH
		;;
	river)
		cd dot_river
		./autoconf deploy
		cd $RST_PATH
		;;
	dwm)
		cd dot_dwm
		./autoconf deploy
		cd $RST_PATH
		;;
	*) echo 
		echo "No session since SESSION = $SESSION"
		;;
esac


echo "Installing GPU drivers"
case "$GPU_VENDOR" in
	intel)
		paru -S --needed "${INTEL_PACKAGES[@]}"
		;;
	amd)
		paru -S --needed "${AMD_PACKAGES[@]}"
		;;
	nvidia)
		paru -S --needed "${NVIDIA_PACKAGES[@]}"
		;;
esac
echo "$SEPARATOR"


echo "Installing session needed packages"
case "$SESSION" in
	hyprland)
		paru -S --needed "${HYPR_SESSION[@]}"
		;;
	river)
		paru -S --needed "${RIVER_SESSION[@]}"
		;;
	dwm)
		paru -S --needed "${DWM_SESSION[@]}"
		;;
	*)
		echo "No session since SESSION = $SESSION"
		;;
esac
echo "$SEPARATOR"


if [[ "$STEAM" == "1" ]]; then
	paru -S --needed steam
fi


if [[ "$LATEX" == "1" ]]; then
	paru -S --needed texlive biber texlive-luatex texlive-lang
fi


if [[ "$MINECRAFT" == "1" ]]; then
	paru -S --needed prismlauncher
fi


if [[ "$RUST" == "1" ]]; then
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi


if [[ "$ASEPRITE" == "1" ]]; then
	paru -S --needed aseprite
fi


if [[ "$BETTERBIRD" == "1" ]]; then
	paru -S --needed betterbird-bin # AUR
fi


if [[ "$NEOTHESIA" == "1" ]]; then
	paru -S --needed neothesia
fi


if [[ "$REIHA" == "1" ]]; then
	curl -L -o reiha https://github.com/Barysk/reiha/releases/download/v1.2.0/reiha
	chmod +x reiha
	sudo mv reiha /usr/local/bin/
fi


if [[ "$TESUTERU" == "1" ]]; then
	curl -L -o tesuteru https://github.com/Barysk/testownik_cli/releases/download/ver1.0.1/tesuteru
	chmod +x tesuteru
	sudo mv tesuteru /usr/local/bin/
fi


if [[ "$TOOLS" == "1" ]]; then
	git clone https://github.com/Barysk/tools
	cd tools/
	./build_tools.bash
	./install.bash
	cd $RST_PATH
fi
echo "$SEPARATOR"


echo "removing $TMP_FOLDER at $HOME"
cd $HOME
rm -rf $TMP_FOLDER
echo "$SEPARATOR"


echo "updating tldr"
tldr --update
echo "$SEPARATOR"


echo "setting up auto-cpufreq"
sudo auto-cpufreq --install
echo "$SEPARATOR"


echo "enabling bluetooth.service"
sudo systemctl enable --now bluetooth.service
echo "$SEPARATOR"


echo "setting pcmanfm as a deafault file explorer"
xdg-mime default pcmanfm.desktop inode/directory
echo "$SEPARATOR"


echo "All done!"
echo ""


echo "Reboot is advised"
echo "$SEPARATOR"


echo "Reboot?"
read -rp "[ Y/n ]: " choice
if [[ "$choice" =~ ^[Yy]$ ]]; then
	reboot
fi


################################################################################

# Copyright (c) 2025 Barys Kamaroŭ. All Rights Reserved.
